### ISSUE TITLE
Clase de Configuración

### ISSUE THREAD

**Issue by joelibaceta** [mercadopago/px-java#1]
Crear un objeto que administre la configuración para la librería (Credenciales, URL Base) , esta debe ser accesible en cualquier momento durante el ciclo de vida de la aplicación, las credenciales deben poder ser refrescadas en caso sea necesario.

Las formas de configuración deben ser :

- [ ]  Atributo por Atributo.
- [ ]  Un Mapa o Hash de valores 
- [ ]  Un Archivo de Propiedades

Las características configurables pueden ser:

- client_secret
- client_id
- access_token
- app_id 
- base_url : _Si esta variable no es asignada toma por defecto el valor de https://api.mercadopago.com_

**Ejemplo de resultado esperado:**

```Java
MercadoPago.Settings.setClientSecret("CLIENT_SECRET");
MercadoPago.Settings.setClientID("CLIENT_ID");

System.out.println(MercadoPago.Settings.getClientID()); // CLIENT_ID
```

**Comment by eduardopaoletta** [comment]
Joel, 
Estaba viendo el uso esperado de esta clase que estoy programando...
Veo que especificas que se acceda a los atributos del settings como si fuera una variable publica o una propiedad...
Por lo general es una buena practica acceder con getters/setters.

`MercadoPago.Settings.setClientSecret("CLIENT_SECRET");`
`System.out.println(MercadoPago.Settings.getClientSecret()); // CLIENT_SECRET `

Lo puedo hacer como quieras, prefiero sacarme la duda ahora.

**Comment by joelibaceta** [comment]
Eduardo, 
Tenes razón, me parece correcto el uso de Setters y Getters, ya que es lo mas idiomático en Java, y es parte de la vision tratar de ser lo mas transparentes para el usuario final, te dejaría la consulta tambien si una opcion tambien considerar a ClientSecret como una constante, ya que se inicializan una única vez.

**Comment by eduardopaoletta** [comment]
Constantes no pueden ser, ya que no se setean en tiempo de ejecucion. Podrian ser finals, pero solo podes asignarlos en constructores. Justamente, para esas cosas se usan los setters. Seria simple, podria ignorar una asignacion a una variable que ya tiene valor, o mejor aun podria disparar una excepcion. 

Otra consulta ya que lo mencione. Vendria bien crear una clase que herede de excepciones, para manejar excepciones de la sdk. Me imagino que vendria bien tener como atributos el request_id, tal vez el status_code despues de hacer la llamada rest.

Y una ultima, es muy raro usar YAML en java. Se puede implementar sin problemas, pero no veo que alguien lo vaya a usar. (es una opinion mia :P)

**Comment by joelibaceta** [comment]
De acuerdo con lo de la clase de excepciones es el approach que se ha ido manejando.

De acuerdo con lo de YAML, lo reemplace por el .properties que es mas usado en Java.
